# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Jobs
env: # Or as an environment variable
  SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

on:
  push:
    branches:
    - main
    - add_github_actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: build
      run: |
        npm install
    - name: develop
      run: |
        echo "Hello"
        echo $SPACE_ID
        ls -la